#!/usr/bin/perl

$letra_anterior = "B";
$directorio = "/var/lib/httpd/htdocs/biblio/descriptores/";

$contador=1;

$archivo= $letra_anterior.".html";
open HTML, ">".$directorio.$archivo;

open DESC,"<".$directorio."desc";
while (<DESC>) {
$renglon = $_;
($letra_actual) = ($renglon =~ /(.)/);

if ($letra_actual ne $letra_anterior){
print HTML "</UL>\n";
print HTML "</BODY></HTML>\n";
close HTML;

$contador = 1;
$archivo = $letra_actual.".html";
open HTML, ">".$directorio.$archivo;
print HTML "<HTML><TITLE></TITLE><BODY>\n";
print HTML "<UL>\n";
print `mkdir $directorio/$letra_actual`;
}
#$archivo_secuencial = $letra_actual."_".$contador.".html";
#print HTML "<LI><A HREF= \"".$letra_actual."/".$archivo_secuencial."\">";

print HTML "<LI><A HREF=\"http://pamela.efn.uncor.edu/cgi-bin/new_search.pl/consulta=".$renglon."\">",$renglon,"</A>";

$letra_anterior=$letra_actual;
$contador ++;
}

close HTML;
close DESC;

exit (0);

